spring:
  application:
    name: fakeshop

  datasource:
    url: jdbc:postgresql://fakeshop.cwfiovr0ofdt.eu-central-1.rds.amazonaws.com:5432/postgres # CHANGE!
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12341234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.amazonaws.xray: DEBUG

application:
  aws:
    access-key: ???
    secret-key: ???
  sqs:
    url: https://sqs.eu-central-1.amazonaws.com/528420014452/fakeshop
